{% set version = '1.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bigstep
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bigstep_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bigstep/bigstep_{{ version }}.tar.gz
  sha256: 02ad13485abc3f09dc0bda61efa6886becde9d6969d32eefdfc5622ce90ef779

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r.utils
    - r-rcppeigen
    - r-bigmemory
    - r-magrittr
    - r-matrixstats
    - r-speedglm
  run:
    - r-base
    - r-r.utils
    - r-rcppeigen
    - r-bigmemory
    - r-magrittr
    - r-matrixstats
    - r-speedglm

test:
  commands:
    - $R -e "library('bigstep')"           # [not win]
    - "\"%R%\" -e \"library('bigstep')\""  # [win]

about:
  home: http://github.com/pmszulc/bigstep
  license: GPL-3
  summary: Selecting linear and generalized linear models for large data sets using modified
    stepwise procedure and modern selection criteria (like modifications of Bayesian
    Information Criterion). Selection can be performed on data which exceed RAM capacity.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bigstep
# Type: Package
# Title: Stepwise Selection for Large Data Sets
# Version: 1.0.3
# Date: 2019-7-17
# Authors@R: person("Piotr", "Szulc", email = "piotr.michal.szulc@gmail.com", role = c("aut", "cre"))
# Description: Selecting linear and generalized linear models for large data sets using modified stepwise procedure and modern selection criteria (like modifications of Bayesian Information Criterion). Selection can be performed on data which exceed RAM capacity.
# License: GPL-3
# URL: http://github.com/pmszulc/bigstep
# BugReports: http://github.com/pmszulc/bigstep/issues
# Depends: R (>= 3.5.0)
# Imports: bigmemory, magrittr, matrixStats, R.utils, RcppEigen, speedglm, stats, utils
# Suggests: devtools, knitr, rmarkdown, testthat
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-07-23 07:15:30 UTC; user
# Author: Piotr Szulc [aut, cre]
# Maintainer: Piotr Szulc <piotr.michal.szulc@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-07-25 23:10:02 UTC
