travis:
  secure:
    BINSTAR_TOKEN: J37qajfJbjoihRcZup5+cfkCATvovIQ38cUa07FXYmVOVf29LvhSZPBOlQS66m6QITHRGXW9WxXm35Eztjj0fi0Pwpw1UJDoveHLCDiuECZlRQtukatb6nMRhAQYhogWDK/dL1qPg/0i3O1Clx0BMUnw3RHjFNztk7CnSyhrq/+rNHc3s5eHsc93CG7JWQHeVA157n2IjLSkyQDPdToaUgSU1VKZJONpJq7zHFIFML+C6RubyG7SSYkX928jegnOsmbnP8fOAYuEnLsciw/a8aDCoKF2XnbK4uoc5jYHPVNDuA7O19JGRKThnyemVgFIeyS5QDPUHUqbOCQ0aiVf18LFgwGTSZf3UJOkdFxT17AB2LGFO0Efvp2hBcqOjjDL/JAoXZNijHMQPQz2eaF+ClynlFNO9ZOsUiiFApXb16FwR+RP2sD6v0qBJncZX9uOYbwtLvuvKGSXIAN7fx9LDqHmPmnYCx5e0w8XJI3kVPd/Ojqdf7xRUWSTakKa+fB1EPstyydqHkN+MJ4VMXG7goKKkJIxSH1bJW+7laCopfLxqgvNig+a7CB0ZRuWhi4pZtTyKxhxzW5HIgQaFMGYwswCr3nbGbXw86I/sU5pNIJw4HXjPAZQmVteRjOAmI1RZ9AwXZguy8KW09CNP1JS72vZKmwwa5jPX5fi+E2CZdw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
